### ISSUE TITLE
Undefine function.

### ISSUE THREAD

**Issue by zhouhoo** [amirouche/AjguDB#9]
In examples/test.py, concept_to_trigrams() function is undefine.  Do you miss it or it means to  words_to_trigrams() function?

**Comment by amirouche** [comment]
Yes probably. Can you tell me which revision do you use because this is not the master branch. I will bring back that script if you want.

**Comment by zhouhoo** [comment]
Thank you, I just clone the newest master branch, and build locally.

**Comment by amirouche** [comment]
Let me now if you have issues. By the way wiredtiger 2.9.0 was releaed recently.
